version: "3.0"
services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5430:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - /Users/simoaddoumi/Documents/docker-review-app/git-docker-kubernetes-review/data:/var/lib/postgresql/data

  recap-new:
    container_name: recap-new
    image: mohammedaddoumi/recap-new:latest
    ports:
      - 8085:8085
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_PASSWORD: password